=== ASHCO-2019/real-world-enterprise-reports-using-vb6-vb.net/BookCode/Chapter6/VB6/Requester.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="Requester"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="Requester">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no"/>
<od:index index-name="ProductID" index-key="ProductID " primary="no" unique="no" clustered="no"/>
<od:index index-name="ProductRequester" index-key="ProductID " primary="no" unique="no" clustered="no"/>
<od:index index-name="SourceID" index-key="SourceID " primary="no" unique="no" clustered="no"/>
<od:index index-name="SourceRequester" index-key="SourceID " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Salutation" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="6"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LastName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FirstName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Address1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Address2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="City" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="25"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="State" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Zip" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ProductID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SourceID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Amount" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ASHCO-2019/real-world-enterprise-reports-using-vb6-vb.net/BookCode/Chapter6/VB6/Requester.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Requester.xsd">
<Requester>
<ID>1</ID>
<Salutation>Mr.</Salutation>
<LastName>Bush</LastName>
<FirstName>George</FirstName>
<Address1>123 Main Street</Address1>
<City>Anytown</City>
<State>NJ</State>
<Zip>12345</Zip>
<ProductID>1</ProductID>
<SourceID>9</SourceID>
<Amount>330</Amount>
</Requester>
<Requester>
<ID>2</ID>
<Salutation>Mr.</Salutation>
<LastName>Clinton</LastName>
<FirstName>Bill</FirstName>
<Address1>210 Little Rock Lane</Address1>
<City>Starrville</City>
<State>NY</State>
<Zip>10024</Zip>
<ProductID>2</ProductID>
<SourceID>8</SourceID>
<Amount>214</Amount>
</Requester>
<Requester>
<ID>3</ID>
<Salutation>Mr.</Salutation>
<LastName>Reagan</LastName>
<FirstName>Ronald</FirstName>
<Address1>345 President Drive</Address1>
<City>Bel Air</City>
<State>CA</State>
<Zip>90210</Zip>
<ProductID>3</ProductID>
<SourceID>7</SourceID>
<Amount>45.32</Amount>
</Requester>
<Requester>
<ID>4</ID>
<Salutation>Mr.</Salutation>
<LastName>Carter</LastName>
<FirstName>Jimmy</FirstName>
<Address1>100 Peanut Road</Address1>
<City>Plains</City>
<State>GA</State>
<Zip>19734</Zip>
<ProductID>3</ProductID>
<SourceID>6</SourceID>
<Amount>0.23</Amount>
</Requester>
<Requester>
<ID>5</ID>
<Salutation>Mr.</Salutation>
<LastName>Ford</LastName>
<FirstName>Gerald</FirstName>
<Address1>430 Somerset Court</Address1>
<City>Lansing</City>
<State>MI</State>
<Zip>71344</Zip>
<ProductID>3</ProductID>
<SourceID>3</SourceID>
<Amount>12.65</Amount>
</Requester>
<Requester>
<ID>6</ID>
<Salutation>Mr.</Salutation>
<LastName>Nixon</LastName>
<FirstName>Richard</FirstName>
<Address1>7834 Main Street</Address1>
<City>Princeton</City>
<State>NJ</State>
<Zip>45646</Zip>
<ProductID>3</ProductID>
<SourceID>3</SourceID>
<Amount>453.12</Amount>
</Requester>
<Requester>
<ID>7</ID>
<Salutation>Mr.</Salutation>
<LastName>Johnson</LastName>
<FirstName>Lyndon</FirstName>
<Address1>234 First Street</Address1>
<City>Mobile</City>
<State>AL</State>
<Zip>23655</Zip>
<ProductID>7</ProductID>
<SourceID>2</SourceID>
</Requester>
<Requester>
<ID>8</ID>
<Salutation>Mr.</Salutation>
<LastName>Kennedy</LastName>
<FirstName>John</FirstName>
<Address1>456 Second Street</Address1>
<Address2>Apt 3D</Address2>
<City>Flint</City>
<State>MI</State>
<Zip>34535</Zip>
<ProductID>8</ProductID>
<SourceID>2</SourceID>
</Requester>
<Requester>
<ID>9</ID>
<Salutation>Mr.</Salutation>
<LastName>Eisenhower</LastName>
<FirstName>Dwight</FirstName>
<Address1>323 Third Street</Address1>
<City>Augusta</City>
<State>GA</State>
<Zip>35353</Zip>
<ProductID>9</ProductID>
<SourceID>1</SourceID>
</Requester>
<Requester>
<ID>10</ID>
<Salutation>Mr.</Salutation>
<LastName>Truman</LastName>
<FirstName>Harry</FirstName>
<Address1>947 Fourth Street</Address1>
<City>Tampa</City>
<State>FL</State>
<Zip>57657</Zip>
<ProductID>1</ProductID>
<SourceID>1</SourceID>
</Requester>
<Requester>
<ID>11</ID>
<Salutation>Mr.</Salutation>
<LastName>Roosevelt</LastName>
<FirstName>Franklin</FirstName>
<Address1>56 Fifth Street</Address1>
<City>Elmira</City>
<State>NY</State>
<Zip>12312</Zip>
<ProductID>2</ProductID>
<SourceID>7</SourceID>
</Requester>
<Requester>
<ID>12</ID>
<Salutation>Mr.</Salutation>
<LastName>Hoover</LastName>
<FirstName>Herbert</FirstName>
<Address1>12 Sixth Street</Address1>
<City>Bennington</City>
<State>VT</State>
<Zip>54676</Zip>
<ProductID>6</ProductID>
<SourceID>7</SourceID>
</Requester>
<Requester>
<ID>13</ID>
<Salutation>Mr.</Salutation>
<LastName>Coolodge</LastName>
<FirstName>Calvin</FirstName>
<Address1>844 Seventh Street</Address1>
<City>St. Louis</City>
<State>MO</State>
<Zip>13135</Zip>
<ProductID>6</ProductID>
<SourceID>6</SourceID>
</Requester>
<Requester>
<ID>14</ID>
<Salutation>Mr.</Salutation>
<LastName>Wilson</LastName>
<FirstName>Woodrow</FirstName>
<Address1>8343 Eighth Street</Address1>
<City>Louisville</City>
<State>KY</State>
<Zip>67543</Zip>
<ProductID>6</ProductID>
<SourceID>6</SourceID>
</Requester>
<Requester>
<ID>15</ID>
<Salutation>Mr.</Salutation>
<LastName>Taft</LastName>
<FirstName>William</FirstName>
<Address1>567 Ninth Street</Address1>
<City>Memphis</City>
<State>TN</State>
<Zip>12564</Zip>
<ProductID>6</ProductID>
<SourceID>5</SourceID>
</Requester>
<Requester>
<ID>16</ID>
<Salutation>Mr.</Salutation>
<LastName>Roosevelt</LastName>
<FirstName>Theodore</FirstName>
<Address1>257 Tenth Street</Address1>
<City>Butte</City>
<State>MT</State>
<Zip>97245</Zip>
<ProductID>7</ProductID>
<SourceID>5</SourceID>
</Requester>
<Requester>
<ID>17</ID>
<Salutation>Mr.</Salutation>
<LastName>McKinley</LastName>
<FirstName>William</FirstName>
<Address1>746 Elevnth Street</Address1>
<City>San Diego</City>
<State>CA</State>
<Zip>35626</Zip>
<ProductID>8</ProductID>
<SourceID>4</SourceID>
</Requester>
<Requester>
<ID>18</ID>
<Salutation>Mr.</Salutation>
<LastName>Cleveland</LastName>
<FirstName>Grover</FirstName>
<Address1>34 Twelveth Street</Address1>
<City>Portland</City>
<State>OR</State>
<Zip>35625</Zip>
<ProductID>9</ProductID>
<SourceID>4</SourceID>
</Requester>
<Requester>
<ID>19</ID>
<Salutation>Mr.</Salutation>
<LastName>Harrison</LastName>
<FirstName>Benjamin</FirstName>
<Address1>774 Thirteenth Street</Address1>
<City>Redmond</City>
<State>WA</State>
<Zip>54734</Zip>
<ProductID>1</ProductID>
<SourceID>3</SourceID>
</Requester>
<Requester>
<ID>20</ID>
<Salutation>Mr.</Salutation>
<LastName>Arthur</LastName>
<FirstName>Chester</FirstName>
<Address1>246 Fourteenth Street</Address1>
<City>Reno</City>
<State>NV</State>
<Zip>12321</Zip>
<ProductID>2</ProductID>
<SourceID>3</SourceID>
</Requester>
<Requester>
<ID>21</ID>
<Salutation>Mr.</Salutation>
<LastName>Garfield</LastName>
<FirstName>James</FirstName>
<Address1>22 Fifteenth Street</Address1>
<City>Boise</City>
<State>ID</State>
<Zip>34562</Zip>
<ProductID>5</ProductID>
<SourceID>2</SourceID>
</Requester>
<Requester>
<ID>22</ID>
<Salutation>Mr.</Salutation>
<LastName>Hayes</LastName>
<FirstName>Rutherford</FirstName>
<Address1>55 Sixteenth Street</Address1>
<City>Ottumwa</City>
<State>IA</State>
<Zip>31734</Zip>
<ProductID>5</ProductID>
<SourceID>2</SourceID>
</Requester>
<Requester>
<ID>23</ID>
<Salutation>Mr.</Salutation>
<LastName>Grant</LastName>
<FirstName>Ulysses</FirstName>
<Address1>84 Seventeenth Street</Address1>
<City>Lincoln</City>
<State>NE</State>
<Zip>73125</Zip>
<ProductID>5</ProductID>
<SourceID>1</SourceID>
</Requester>
<Requester>
<ID>24</ID>
<Salutation>Mr.</Salutation>
<LastName>Johnson</LastName>
<FirstName>Andrew</FirstName>
<Address1>35 Eighteenth Street</Address1>
<City>Charleston</City>
<State>SC</State>
<Zip>34565</Zip>
<ProductID>5</ProductID>
<SourceID>5</SourceID>
</Requester>
<Requester>
<ID>25</ID>
<Salutation>Mr.</Salutation>
<LastName>Lincoln</LastName>
<FirstName>Abraham</FirstName>
<Address1>573 Ninteenth Street</Address1>
<City>Goldsboro</City>
<State>NC</State>
<Zip>12572</Zip>
<ProductID>7</ProductID>
<SourceID>5</SourceID>
</Requester>
<Requester>
<ID>26</ID>
<Salutation>Mr.</Salutation>
<LastName>Buchanan</LastName>
<FirstName>James</FirstName>
<Address1>2465 Twentieth Street</Address1>
<City>Boston</City>
<State>MA</State>
<Zip>64325</Zip>
<ProductID>8</ProductID>
<SourceID>4</SourceID>
</Requester>
</dataroot>
